import type { Property, BannerAd } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Executive Mansion in Naguru',
    type: 'House',
    location: 'Naguru',
    price: 3500000000,
    bedrooms: 6,
    bathrooms: 7,
    lotSize: '50 decimals',
    areaSqFt: 6000,
    description: 'A masterpiece of architectural design in the prestigious Naguru hill. This mansion offers panoramic views of Kampala.',
    features: ['Swimming Pool', 'Home Gym', 'Cinema', 'Rooftop Terrace', 'Mature Garden'],
    imageIds: ['property_1_1', 'property_1_2'],
    isPremium: true,
    verified: true,
    broker: { name: 'Prestige Properties', phone: '070-112-2334' },
    status: 'approved',
    landTenure: 'Mailo',
  },
  {
    id: '2',
    title: 'Prime Plot in Nakasero',
    type: 'Land',
    location: 'Nakasero',
    price: 1800000000,
    lotSize: '40 decimals',
    description: 'Rare opportunity to acquire a prime plot of land in the heart of Nakasero. Ideal for a high-end residence or commercial building.',
    features: ['Tarmac Access', 'Premium Location', 'Secure Neighborhood'],
    imageIds: ['property_2_1'],
    isPremium: true,
    broker: { name: 'City Real Estate', phone: '075-887-7665' },
    status: 'approved',
    landTenure: 'Freehold',
  },
  {
    id: '3',
    title: 'Apartment for rent in Najjera',
    type: 'Apartment',
    location: 'Najjera',
    price: 900000,
    rental: true,
    rentalPeriod: 'month',
    bedrooms: 2,
    bathrooms: 2,
    description: 'Modern 2-bedroom apartment for rent in a gated community in Najjera.',
    features: ['Balcony', 'Paved Parking', 'Security'],
    imageIds: ['property_3_1'],
    isPremium: false,
    broker: { name: 'Najjera Homes', phone: '079-111-3333' },
    status: 'approved',
    landTenure: 'Leasehold',
  },
  {
    id: '4',
    title: 'House in Namugongo',
    type: 'House',
    location: 'Namugongo',
    price: 300000000,
    bedrooms: 4,
    bathrooms: 4,
    description: 'A 4-bedroom house in Namugongo, close to the martyr\'s shrine.',
    features: ['Large Compound', 'Wall Fence', 'Quiet Neighborhood'],
    imageIds: ['property_4_1'],
    isPremium: false,
    broker: { name: 'Sanctuary Homes', phone: '077-444-5555' },
    status: 'approved',
    landTenure: 'Freehold',
  },
    {
    id: '5',
    title: 'Land for sale in Kireka',
    type: 'Land',
    location: 'Kireka',
    price: 80000000,
    lotSize: '12 decimals',
    description: 'A 12-decimal plot in Kireka suitable for residential purposes.',
    features: ['Developing Area', 'Good Access Road', 'Land Title'],
    imageIds: ['property_5_1'],
    isPremium: false,
    broker: { name: 'Kireka Land Dealers', phone: '078-666-7777' },
    status: 'approved',
    landTenure: 'Mailo',
  },
  {
    id: '7',
    title: '50x100ft Plot in Gayaza',
    type: 'Land',
    location: 'Gayaza',
    price: 15000000,
    lotSize: '50x100 ft',
    description: 'An affordable plot in the fast-growing neighborhood of Gayaza, perfect for building your dream family home. Comes with a ready land title.',
    features: ['Ready Title', 'Developing Area', 'Good Access'],
    imageIds: ['property_7_1'],
    isPremium: false,
    broker: { name: 'Sarah Musisi', phone: '071-123-4567' },
    status: 'approved',
    landTenure: 'Kibanja',
  },
  {
    id: '8',
    title: '3-Bedroom House for Rent in Naalya',
    type: 'House',
    location: 'Naalya',
    price: 1500000,
    rental: true,
    rentalPeriod: 'month',
    furnished: true,
    bedrooms: 3,
    bathrooms: 3,
    areaSqFt: 1800,
    description: 'A beautiful 3-bedroom house for rent in a serene and secure Naalya neighborhood. Features a spacious compound, modern finishes, and ample parking space.',
    features: ['Modern Kitchen', 'Secure Wall', 'Large Compound', 'Servant Quarters'],
    imageIds: ['property_8_1'],
    isPremium: true,
    broker: { name: 'Moses Byamukama', phone: '072-987-6543' },
    status: 'approved',
    landTenure: 'Leasehold',
  },
  {
    id: '9',
    title: '25-decimal Land in Mukono',
    type: 'Land',
    location: 'Mukono',
    price: 10000000,
    lotSize: '25 decimals',
    description: 'Excellent value for a 25-decimal plot in a prime area of Mukono, perfectly suitable for residential construction or farming.',
    features: ['Easy Access', 'Growing Community', 'Power and Water nearby'],
    imageIds: ['property_9_1'],
    isPremium: false,
    broker: { name: 'Grace Nakandi', phone: '073-111-2222' },
    status: 'approved',
    landTenure: 'Leasehold',
  },
  {
    id: '10',
    title: 'Modern 2-Bedroom Apartment in Kiwatule',
    type: 'Apartment',
    location: 'Kiwatule',
    price: 220000000,
    furnished: true,
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1100,
    description: 'A stylish and modern 2-bedroom apartment located in Kiwatule with great amenities. Close to shopping centers, international schools, and public transport.',
    features: ['Balcony', 'Ample Parking', '24/7 Security', 'Gym Access'],
    imageIds: ['property_10_1'],
    isPremium: true,
    broker: { name: 'Emmanuel Okot', phone: '074-333-4444' },
    status: 'approved',
    landTenure: 'Mailo',
  },
  {
    id: '11',
    title: 'Luxury Penthouse with City View',
    type: 'Apartment',
    location: 'Kololo',
    price: 2500000000,
    furnished: true,
    bedrooms: 4,
    bathrooms: 5,
    areaSqFt: 3500,
    description: 'Experience unparalleled luxury living in this stunning penthouse apartment in the heart of Kololo. It offers breathtaking city views, world-class amenities, and exquisite design.',
    features: ['Rooftop Terrace', 'Private Jacuzzi', 'Concierge Service', 'City View'],
    imageIds: ['property_11_1', 'property_11_2'],
    isPremium: true,
    verified: true,
    broker: { name: 'Isabella Rossi', phone: '070-999-0000' },
    status: 'approved',
    landTenure: 'Mailo',
  },
  {
    id: '12',
    title: 'Single Room Hostel in Banda',
    type: 'Hostel',
    location: 'Banda',
    price: 1300000,
    rental: true,
    rentalPeriod: 'semester',
    bedrooms: 1,
    bathrooms: 1,
    areaSqFt: 150,
    furnished: true,
    description: 'Affordable single room hostel in Banda, ideal for students. Price is per semester.',
    features: ['Shared Kitchen', '24/7 Security', 'Close to Campus', 'Furnished'],
    imageIds: ['property_12_1'],
    isPremium: false,
    broker: { name: 'David Kintu', phone: '075-555-6666' },
    status: 'approved',
    landTenure: 'Leasehold',
  },
  {
    id: '13',
    title: 'Commercial Space in Nakawa',
    type: 'Apartment',
    location: 'Nakawa',
    price: 5000000,
    rental: true,
    rentalPeriod: 'month',
    areaSqFt: 2500,
    description: 'Large commercial space for rent in Nakawa, suitable for office or retail. High-traffic area.',
    features: ['Main Road Access', 'Ample Parking', 'High Visibility'],
    imageIds: ['property_13_1'],
    isPremium: true,
    broker: { name: 'PropertyLink Uganda', phone: '076-123-9876' },
    status: 'approved',
    landTenure: 'Leasehold',
  },
  {
    id: '14',
    title: 'Family Home in Ntinda',
    type: 'House',
    location: 'Ntinda',
    price: 450000000,
    bedrooms: 4,
    bathrooms: 3,
    lotSize: '15 decimals',
    description: 'Spacious family home in a quiet residential area of Ntinda.',
    features: ['Garden', 'Servant Quarters', 'Secure Wall'],
    imageIds: ['property_14_1'],
    isPremium: false,
    broker: { name: 'John Bosco', phone: '078-456-1234' },
    status: 'approved',
    landTenure: 'Freehold',
  },
  {
    id: '15',
    title: '1 Acre Land in Entebbe',
    type: 'Land',
    location: 'Entebbe',
    price: 250000000,
    lotSize: '1 Acre',
    description: 'Prime 1-acre land near the airport, ideal for commercial development or residential estate.',
    features: ['Lake Views', 'Easy Airport Access', 'Ready Title'],
    imageIds: ['property_15_1'],
    isPremium: true,
    broker: { name: 'Entebbe Properties', phone: '079-987-1234' },
    status: 'approved',
    landTenure: 'Mailo',
  },
  {
    id: '16',
    title: '2-Bedroom Apartment in Kira',
    type: 'Apartment',
    location: 'Kira',
    price: 850000,
    rental: true,
    rentalPeriod: 'month',
    bedrooms: 2,
    bathrooms: 2,
    description: 'Newly built 2-bedroom apartment for rent in Kira.',
    features: ['Modern Finishes', 'Paved Compound', 'Gated Community'],
    imageIds: ['property_16_1'],
    isPremium: false,
    broker: { name: 'Kira Rentals', phone: '077-321-6547' },
    status: 'approved',
    landTenure: 'Leasehold',
  },
  {
    id: '17-pending',
    title: 'Commercial Building in City Center',
    type: 'Apartment',
    location: 'Nakasero',
    price: 15000000,
    rental: true,
    rentalPeriod: 'month',
    areaSqFt: 5000,
    description: 'A newly submitted commercial space in the bustling center of Nakasero, awaiting approval.',
    features: ['High Traffic', 'Roadside', 'New Construction'],
    imageIds: ['property_13_1'],
    isPremium: false,
    broker: { name: 'City Brokers Inc.', phone: '075-123-4567' },
    status: 'pending',
    landTenure: 'Freehold',
  },
  {
    id: '18-pending',
    title: 'Cozy Bungalow in Munyonyo',
    type: 'House',
    location: 'Munyonyo',
    price: 350000000,
    bedrooms: 3,
    bathrooms: 2,
    lotSize: '15 decimals',
    description: 'Charming 3-bedroom bungalow in the quiet and secure neighborhood of Munyonyo. Submitted for review.',
    features: ['Garden', 'Quiet Area', 'Wall Fence'],
    imageIds: ['property_4_1'],
    isPremium: false,
    broker: { name: 'Lakeview Realtors', phone: '078-987-6543' },
    status: 'pending',
    landTenure: 'Mailo',
  },
];


export const bannerAds: BannerAd[] = [
  {
    id: 'ad1',
    title: 'List Your Property, Reach Millions',
    description: 'Get your property seen by the right buyers. Go Premium for maximum visibility.',
    link: '/dashboard/add-listing',
    imageId: 'banner_ad_1',
  },
  {
    id: 'ad2',
    title: 'Find Your Dream Land in Uganda',
    description: 'Explore exclusive land listings in serene and developing locations across the country.',
    link: '#properties',
    imageId: 'banner_ad_2',
  },
];
